spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    mode: HTML
    servlet:
      content-type: text/html
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
      freemarker:
        cache: false    #页面不加载缓存，修改即时生效
mybatis:
  type-aliases-package: com.gaoxi.GaoxiUser.domain
  mapper-locations: classpath:mapper/*.xml

server:
  port: 9090

