spring:
  application:
    name: gaoxi-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

server:
  # 服务端口
  port:8070

management:
  # 端点检查（健康检查）
  endpoints:
    web:
      exposure:
        include: "*"

